Vagrant.configure("2") do |config|
	
	# Specify the base box
	config.vm.box = "../../packer/centos_base.box"

    #ssh configuration
    config.ssh.username = "admin"
    config.ssh.private_key_path= "../../packer/acit_4640_base/acit_admin_id_rsa"

	# Setup port forwarding
    config.vm.network :forwarded_port, guest: 80, host: 50080
    config.vm.network :forwarded_port, guest: 22, host: 50022
	config.vm.network :forwarded_port, guest: 443, host: 50443


    # Setup synced folder
    config.vm.synced_folder "./configs/", "/configs", create: true, group: "wheel", owner: "admin"

    # VM specific configs
    config.vm.provider "virtualbox" do |vb|
    	vb.name = "ACIT_4640 Vagrant"
        vb.customize ["modifyvm", :id, "--memory", "1024"]
    end

    # Shell provisioning
    config.vm.provision "shell" do |s|
    	s.path = "provision/wp_setup.sh"
    end
end