---

#nginx
- name: install nginx
  yum:
    name: nginx
    state: latest
    disable_gpg_check: yes

- name: copy nginx files
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Start nginx and enable
  service:
    name: nginx
    state: started
    enabled: yes

#firewalld
- name: Add https
  firewalld:
    service: https
    permanent: yes
    immediate: yes
    state: enabled

- name: Add http
  firewalld:
    service: http
    permanent: yes
    immediate: yes
    state: enabled

#force all handlers to run - so all db updates will take effect  
- meta: flush_handlers
...
